get http://localhost:8080/user-api/users



### route for registration
post http://localhost:8080/user-api/register
Content-Type: application/json

{
  "userId": 33,
  "firstName" : "Sandeep",
  "lastName" : "Monkolla", 
  "email" : "sandeep@westagilelabs.com", 
  "password": "sandeep@123"
}





###Login route
post http://localhost:8080/user-api/login
Content-Type: application/json

{
  "email" : "Sandeep@westagilelabs.com",
  "password": "sandeep@123"

}



### admin to get all projects
get http://localhost:8080/admin-api/projects


### admin to get the project details by id
get http://localhost:8080/admin-api/project/4



### Creating a project 
post http://localhost:8080/admin-api/project
Content-Type: application/json

{
  "GdoId" : 31,
  "projectId": 4,
  "projectName": "Pulse",
  "client": "Vamsi",
  "clientAccountManger": "Sashi",
  "statusOfProject": "In progress",
  "projectStartDate":"2023-03-10",
  "projectEndDate": "2023-03-12",
  "projectFitnessIndicator": "Amber",
  "domainOfProject": "Node", 
  "typeOfProject": "Development",
  "teamSize": 1
}


### projects under gdo 
get http://localhost:8080/gdo-api/gdo/31/projects


### projects under gdo based on project id
get http://localhost:8080/gdo-api/gdo/31/projects/4


### Role mapping to the registered users.
put http://localhost:8080/super-admin-api/role-update
Content-Type: application/json

{
  "userId" : 31, 
  "role" : "GDO"
}
