###Login route
post http://localhost:8080/user-api/login
Content-Type: application/json

{
  "email" : "Alam.sample@westagilelabs.com",
  "password": "Alam@123"
}


### projects under gdo 
get http://localhost:8080/gdo-api/gdo/31/projectPortfolioDashboard
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ2RvIiwiZW1haWwiOiJBbGFtLnNhbXBsZUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY4MDA4MDQ1NywiZXhwIjoxNjgwOTQ0NDU3fQ.jB-EdQMrv2cjbqCI9bobtzI56dCxJcFx9Jc3-pl1WAE




# ### projects under gdo based on project id
# # get http://localhost:8080/gdo-api/project/2
# get http://localhost:8080/gdo-api/gdo/201/projectDetailedView
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ2RvIiwiZW1haWwiOiJBbGFtLnNhbXBsZUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY4MDA4MDQ1NywiZXhwIjoxNjgwOTQ0NDU3fQ.jB-EdQMrv2cjbqCI9bobtzI56dCxJcFx9Jc3-pl1WAE




### concerns under gdo 
get http://localhost:8080/gdo-api/gdo/21/concerns
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ2RvIiwiZW1haWwiOiJTYW5kZWVwQHdlc3RhZ2lsZWxhYnMuY29tIiwiaWF0IjoxNjc4NzA3MTczLCJleHAiOjE2Nzg3OTM1NzN9.lKQGOTCDsD-BC_dflTHNMWSB1Ti-Tiz_ufN3o83tfnk



### to add team members
post http://localhost:8080/gdo-api/gdo/71/add-team
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ2RvIiwiZW1haWwiOiJTYW5kZWVwQHdlc3RhZ2lsZWxhYnMuY29tIiwiaWF0IjoxNjc4NzAzMTIzLCJleHAiOjE2Nzg3ODk1MjN9._hjuzUjg9SVGsSi4j_NDF327-oJIAhfeYsndZx0mdzA

{
  "empId":922,
  "firstName":"sekhar",
  "role":"testing",
  "startDate":"2023/03/10",
  "endDate":"",
  "status":"In Progress",
  "billingStatus":"billed",
  "exposedToCustomer":"yes",
  "allocationType":"permenant" ,
  "projectId": 10
}


### raise a resource request
post http://localhost:8080/gdo-api/gdo/201/raise-resource-request
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiZ2RvIiwiZW1haWwiOiJTYW5kZWVwQHdlc3RhZ2lsZWxhYnMuY29tIiwiaWF0IjoxNjc4NzA3MTczLCJleHAiOjE2Nzg3OTM1NzN9.lKQGOTCDsD-BC_dflTHNMWSB1Ti-Tiz_ufN3o83tfnk

{
  "gdoId" : 201,
  "projectId" : 10,
  "requestDesc" : "Resource request is raised"
}