### getting all the project updates by project manager
get http://localhost:8080/manager-api/project/1/all-updates
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibWFuYWdlciIsImVtYWlsIjoiSGFyaUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY3ODcwODg5MiwiZXhwIjoxNjc4Nzk1MjkyfQ.hhibzm9XAJLR2cdOxxMxu812AVIiIrtcvnsWPp0fGrY


### getting last week updates
get http://localhost:8080/manager-api/project/1/2-week-updates
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibWFuYWdlciIsImVtYWlsIjoiSGFyaS5zYW1wbGVAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg5NzgzMjAsImV4cCI6MTY3OTg0MjMyMH0.4c66RLapn3bcmozMmO0hY7kuuIdxWqx2dZ2Ym0jSU6o



###Login route
post http://localhost:8080/user-api/login
Content-Type: application/json

{
  "email" : "Hari.sample@westagilelabs.com",
  "password": "Hari@123"
}


### getting all the projects under his maintanence
get http://localhost:8080/manager-api/project-manager-id/73
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibWFuYWdlciIsImVtYWlsIjoiSGFyaS5zYW1wbGVAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg5NzgzMjAsImV4cCI6MTY3OTg0MjMyMH0.4c66RLapn3bcmozMmO0hY7kuuIdxWqx2dZ2Ym0jSU6o

### getting all the concerns from all projects

get http://localhost:8080/manager-api/project/2/concerns
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibWFuYWdlciIsImVtYWlsIjoiSGFyaS5zYW1wbGVAd2VzdGFnaWxlbGFicy5jb20iLCJpYXQiOjE2Nzg5NzgzMjAsImV4cCI6MTY3OTg0MjMyMH0.4c66RLapn3bcmozMmO0hY7kuuIdxWqx2dZ2Ym0jSU6o


### Raising an update by the project manager
post http://localhost:8080/manager-api/update
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibWFuYWdlciIsImVtYWlsIjoiSGFyaUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY3ODcwMzc3MywiZXhwIjoxNjc4NzkwMTczfQ.cGCxfEC8BjwX-RQr9hSX3wprXkIqnlsPRqhyyKYr_WM
Content-Type: application/json

{
  "projectId" : 1,
  "userId" : 73,
   "projectStatusUpdate" : "100% completed",
   "date" : "2023-03-10",
   "scheduleStatus" : "None",
   "resourcingStatus" : "Completed",
   "qualityStatus": "Good",
   "waitingForClientinput" : "True"
}

### Raising an concern by the project manager
post http://localhost:8080/manager-api/concern
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoibWFuYWdlciIsImVtYWlsIjoiSGFyaUB3ZXN0YWdpbGVsYWJzLmNvbSIsImlhdCI6MTY3ODcwMzc3MywiZXhwIjoxNjc4NzkwMTczfQ.cGCxfEC8BjwX-RQr9hSX3wprXkIqnlsPRqhyyKYr_WM
Content-Type: application/json

{
  "projectId" : 1,
  "concernRaisedBy" : 72,
   "concernDesc" : "Need review",
   "concernRaisedDate" : "2023-03-13",
   "concernSeverity" : "medium",
   "concernByClient" : "false",
   "concernStatus": "notSolved",
   "concernMitigatedDate" : "2023-03-13"
}