### get all the users
get http://localhost:8080/user-api/users


### route for registration
post http://localhost:8080/user-api/register
Content-Type: application/json

{
  "userId": 999,
  "firstName" : "Chinna",
  "lastName" : "Hanumanthu", 
  "email" : "userusingmymail@gmail.com", 
  "password": "Chinna@123"
}


### route for registration
post http://localhost:8080/user-api/register
Content-Type: application/json

{
  "userId": 21,
  "firstName" : "Sandeep",
  "lastName" : "Monkolla", 
  "email" : "Sandeep@westagilelabs.com", 
  "password": "Sandeep@123"
}


###
post http://localhost:8080/user-api/register
Content-Type: application/json

{
  "userId":2,
  "firstName" : "Varun",
  "lastName" : "B", 
  "email" : "Varun@westagilelabs.com", 
  "password": "Varun@123"
}


###Login route
post http://localhost:8080/user-api/login
Content-Type: application/json

{
  "email" : "Varun@westagilelabs.com",
  "password": "Varun@123"
}


###
post http://localhost:8080/user-api/login
Content-Type: application/json

{
  "email" : "userusingmymail@gmail.com",
  "password": "Sample@9"
}


### Role mapping to the registered users
put http://localhost:8080/user-api/role-update
Content-Type: application/json

{
  "userId" : 2, 
  "role" : "admin"
}


###  forgotten password
post http://localhost:8080/user-api/forgot-password
Content-Type: application/json

{
  "email" : "userusingmymail@gmail.com"
}


### reset the password
post http://localhost:8080/user-api/reset-password/email/userusingmymail@gmail.com
Content-Type: application/json

{
  "otp" : 10431,
  "password" : "Sample@9"
}