### get all the users
get http://localhost:8080/user-api/users


### route for registration
post http://localhost:8080/user-api/register
Content-Type: application/json

{
  "userId": 2000,
  "firstName" : "test",
  "lastName" : "test", 
  "email" : "teset.sample@westagilelabs.com", 
  "password": "test@123"
}


###Login route
post http://localhost:8080/user-api/login
Content-Type: application/json

{
  "email" : "Varun@westagilelabs.com",
  "password": "Varun@123"
}


###   loggin in with personal mail
post http://localhost:8080/user-api/login
Content-Type: application/json

{
  "email" : "userusingmymail@gmail.com",
  "password": "Sample@9"
}



###  forgotten password
post http://localhost:8080/user-api/forgot-password
Content-Type: application/json

{
  "email" : "userusingmymail@gmail.com"
}


### reset the password
post http://localhost:8080/user-api/reset-password/email/userusingmymail@gmail.com
Content-Type: application/json

{
  "otp" : 10431,
  "password" : "Sample@9"
}